### ISSUE TITLE
feat: health record menu 추가

### ISSUE THREAD

**Issue by dev-heeseok** [dev-heeseok/WEB#20]
health record application 의 home 화면을 개발하려고 한다. 
화면 구성은 Github Home page 와 유사한 형태로 개발할 예정이다.

1. NavBar 를 이용하여 Menu 를 추가할 수 있다.
2. Sign-in/up 을 하기 위한 버튼이 존재 

![image](https://user-images.githubusercontent.com/97526196/171625703-dc8cae96-4f04-4410-aae4-e8d4ebafc548.png)

@kimkmin357 @DeukHan 
기본적인 레이아웃 구성을 진행해 보려고 합니다. 
한동안 쉬었으니 다시 버닝해보아요

**Comment by DeukHan** [comment]
열심히 다시 해보겠습니다!
여러모로 뒤숭숭해서 다시 화이팅
